apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pipmerneks
  name: {{.Values.application.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: pipmerneks
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pipmerneks
    spec:
      containers:
      - image: {{.Values.image.repository}}
        name: pipmerneks
        imagePullPolicy: {{.Values.image.pullPolicy}}
        resources: {}
        ports:
          - containerPort: 8090 
status: {}
